import Image from 'next/image';
import type { Attendance, Profile } from '@/lib/supabase';
import { formatTime, monthLabel, recordDate, shiftMonth, statusOf, type AttendanceStatus } from '@/lib/attendance';

export function AppHeader({ profile, signedIn, busy, onSignOut }: { profile: Profile | null; signedIn: boolean; busy: boolean; onSignOut: () => void }) {
 return <header className="topbar"><div className="brand"><Image className="brand-logo" src="/iconic-logo.jpg" alt="ICONIC" width={170} height={68} unoptimized/><div className="brand-title"><strong>Attender</strong><span>ICONIC · Internal Attendance</span></div></div>{signedIn && <div className="header-actions">{profile && <span className="role-label">{profile.role === 'hr' ? 'HR' : 'Employee'}</span>}<button className="quiet" disabled={busy} onClick={onSignOut}>Sign out <span aria-hidden="true">↗</span></button></div>}</header>;
}
export function MonthNavigator({ month, onChange }: { month: string; onChange: (value: string) => void }) {
 return <div className="month-nav" aria-label="Attendance month"><button aria-label="Previous month" onClick={() => onChange(shiftMonth(month, -1))}>←</button><span aria-live="polite">{monthLabel(month)}</span><button aria-label="Next month" onClick={() => onChange(shiftMonth(month, 1))}>→</button></div>;
}
const labels = { pending: 'Pending', 'checked-in': 'Checked In', completed: 'Completed' };
export function StatusBadge({ status }: { status: AttendanceStatus }) { return <span className={`status-badge ${status}`}>{labels[status]}</span>; }
export function AttendanceTable({ rows, zone, month, hr = false, names }: { rows: Attendance[]; zone: string; month: string; hr?: boolean; names?: Map<string, string> }) {
 const columns = hr ? ['Employee', 'Day', 'Date', 'Location', 'In', 'Out', 'Signature', 'Status'] : ['Day', 'Date', 'Location', 'In', 'Out', 'Signature'];
 return <><div className="table-scroll" tabIndex={0} role="region" aria-label="Monthly attendance records"><table><thead><tr>{columns.map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{rows.length ? rows.map(row => {
 const date = recordDate(row, zone);
 return <tr key={row.id}>{hr && <td className="employee-name">{names?.get(row.employee_id) || 'Employee'}</td>}<td>{new Intl.DateTimeFormat('en-GB', { weekday: 'long', timeZone: 'UTC' }).format(new Date(`${date}T12:00:00Z`))}</td><td>{date.split('-').reverse().join('/')}</td><td><span className={`location ${row.location}`}>{row.location === 'office' ? 'Office' : 'Remote'}</span></td><td>{formatTime(row.in_time, zone)}</td><td>{formatTime(row.out_time, zone)}</td><td><span className="signature" aria-label={row.signature_approved ? 'Approved by HR' : 'Not approved'}>{row.signature_approved ? '✓' : '—'}</span></td>{hr && <td><StatusBadge status={statusOf(row)}/></td>}</tr>;
 }) : <tr><td colSpan={columns.length} className="empty">No attendance records{hr ? ' found' : ''} for {monthLabel(month)}.</td></tr>}</tbody></table></div><div className="table-footer"><span className="signature">✓</span> Approved by HR{hr && <span className="pending-note">Pending dates show the request date.</span>}</div></>;
}
export function TodayAttendanceCard({ row, today, zone, busy, location, onLocation, onRequest, onCheckout }: { row?: Attendance; today: string; zone: string; busy: boolean; location: 'office' | 'remote'; onLocation: (location: 'office' | 'remote') => void; onRequest: () => void; onCheckout: (id: string) => void }) {
 const status = row ? statusOf(row) : null;
 const activeEarlier = row && recordDate(row, zone) !== today && !row.out_time;
 return <section className="panel checkin"><div className="today-grid"><div className="today-controls"><div className="section-heading"><span className="step" aria-hidden="true">01</span><h2>{!status ? 'Your Check-In' : status === 'pending' ? 'Check-In Requested' : status === 'checked-in' ? "You're Checked In" : 'Attendance Complete'}</h2></div>{!row ? <><fieldset disabled={busy}><legend>Location</legend><div className="location-options">{(['office', 'remote'] as const).map(value => <label key={value} className={location === value ? 'choice selected' : 'choice'}><input type="radio" name="location" checked={location === value} onChange={() => onLocation(value)}/><span>{value === 'office' ? 'Office' : 'Remote'}</span><span className="radio-dot" aria-hidden="true"/></label>)}</div></fieldset><button className="primary" disabled={busy} onClick={onRequest}>{busy ? 'Sending request…' : 'Request Check-In'}<span aria-hidden="true">→</span></button><p className="fine">Your check-in time will be recorded after HR approves your request.</p></> : <div className="session"><StatusBadge status={status!}/>{status === 'pending' ? <><h3>Waiting for HR Approval</h3><p>Location: {row.location === 'office' ? 'Office' : 'Remote'}</p><button className="primary" disabled>Request sent ✓</button></> : status === 'checked-in' ? <><p className="approval-label">Approved by HR</p><p className="in-time">Check-in: {formatTime(row.in_time, zone)}</p><button className="primary" disabled={busy} onClick={() => onCheckout(row.id)}>{busy ? 'Checking out…' : 'Check Out'}<span aria-hidden="true">→</span></button></> : <><h3>Your day is recorded.</h3><p>No further check-in is needed today.</p></>}{activeEarlier && <p className="fine">Open attendance from {recordDate(row, zone).split('-').reverse().join('/')}. Complete this session before requesting a new check-in.</p>}</div>}</div><aside className="today-summary"><span className="eyebrow">{activeEarlier ? 'OPEN SESSION' : 'TODAY'}</span><p className="summary-date">{new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' }).format(new Date(`${today}T12:00:00Z`))}</p><dl><div><dt>Status</dt><dd>{status ? <StatusBadge status={status}/> : 'Not requested'}</dd></div><div><dt>Location</dt><dd>{row ? row.location === 'office' ? 'Office' : 'Remote' : '—'}</dd></div><div><dt>In</dt><dd>{formatTime(row?.in_time || null, zone)}</dd></div><div><dt>Out</dt><dd>{formatTime(row?.out_time || null, zone)}</dd></div></dl></aside></div></section>;
}
